#ifndef __JIT__
#define __JIT__
#include <msp430.h>
#include <libmsp/mem.h>
#include <libos/checkpoint.h> // Generated by python
#include <libos/global.h>

enum {OPERATING=0, SLEEPING=1, IDLING = 2, IDLING_NO_MEASURE = 4};
extern unsigned mode;
extern unsigned restore_cnt;

extern unsigned chkpt_mask;

//#define PROTECT_BEGIN() \
//	CEINT &= ~CEIE;\
//	chkpt_mask = 1;\
//	checkpoint_manual();\
//	CEINT |= CEIE;
#define PROTECT_BEGIN() \
	__disable_interrupt();\
	chkpt_mask = 1;\
	checkpoint_manual();\
	__enable_interrupt();

#define PROTECT_END() \
	chkpt_mask = 0;

void checkpoint_manual();

#define checkpoint_gpio() \
	p1out_bak = P1OUT;\
	p2out_bak = P2OUT;\
	p3out_bak = P3OUT;\
	p4out_bak = P4OUT;\
	p5out_bak = P5OUT;\
	p6out_bak = P6OUT;\
	p7out_bak = P7OUT;\
	p8out_bak = P8OUT;\
	pjout_bak = PJOUT;\
	p1DIR_bak = P1DIR;\
	p2DIR_bak = P2DIR;\
	p3DIR_bak = P3DIR;\
	p4DIR_bak = P4DIR;\
	p5DIR_bak = P5DIR;\
	p6DIR_bak = P6DIR;\
	p7DIR_bak = P7DIR;\
	p8DIR_bak = P8DIR;\
	pjDIR_bak = PJDIR;

#define restore_gpio() \
	P1OUT = p1out_bak;\
	P2OUT = p2out_bak;\
	P3OUT = p3out_bak;\
	P4OUT = p4out_bak;\
	P5OUT = p5out_bak;\
	P6OUT = p6out_bak;\
	P7OUT = p7out_bak;\
	P8OUT = p8out_bak;\
	PJOUT = pjout_bak;\
	P1DIR = p1DIR_bak;\
	P2DIR = p2DIR_bak;\
	P3DIR = p3DIR_bak;\
	P4DIR = p4DIR_bak;\
	P5DIR = p5DIR_bak;\
	P6DIR = p6DIR_bak;\
	P7DIR = p7DIR_bak;\
	P8DIR = p8DIR_bak;\
	PJDIR = pjDIR_bak; 

extern unsigned p1out_bak;
extern unsigned p2out_bak;
extern unsigned p3out_bak;
extern unsigned p4out_bak;
extern unsigned p5out_bak;
extern unsigned p6out_bak;
extern unsigned p7out_bak;
extern unsigned p8out_bak;
extern unsigned pjout_bak;
extern unsigned p1DIR_bak;
extern unsigned p2DIR_bak;
extern unsigned p3DIR_bak;
extern unsigned p4DIR_bak;
extern unsigned p5DIR_bak;
extern unsigned p6DIR_bak;
extern unsigned p7DIR_bak;
extern unsigned p8DIR_bak;
extern unsigned pjDIR_bak;
#endif
